2023-12-09 19:54:01,898 - ERROR: Помилка обробки команди 2: UserInterface.save_data() missing 1 required positional argument: 'file_format'
2023-12-09 19:54:06,679 - ERROR: Помилка обробки команди 2: UserInterface.save_data() missing 1 required positional argument: 'file_format'
2023-12-09 19:54:08,097 - ERROR: Помилка обробки команди 2: UserInterface.save_data() missing 1 required positional argument: 'file_format'
2023-12-09 19:54:08,515 - ERROR: Помилка обробки команди 2: UserInterface.save_data() missing 1 required positional argument: 'file_format'
2023-12-09 19:54:08,929 - ERROR: Помилка обробки команди 2: UserInterface.save_data() missing 1 required positional argument: 'file_format'
2023-12-09 19:54:09,410 - ERROR: Помилка обробки команди 2: UserInterface.save_data() missing 1 required positional argument: 'file_format'
2023-12-13 14:23:43,591 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016C527D2610>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-13 14:37:02,630 - INFO: Running Lab 1
2023-12-13 14:37:44,191 - INFO: Running Lab 1
2023-12-13 14:38:09,097 - INFO: Running Lab 1
2023-12-13 14:40:53,715 - INFO: Running Lab 1
2023-12-13 14:45:11,268 - INFO: Running Lab 2
2023-12-13 14:45:23,602 - INFO: Running Lab 1
2023-12-13 14:47:58,823 - INFO: Running Lab 8
2023-12-13 14:48:08,417 - INFO: Running Lab 7
2023-12-13 14:48:13,778 - INFO: Lab 7 completed
2023-12-13 14:48:16,868 - INFO: Running Lab 5
2023-12-13 14:48:24,661 - INFO: Lab 5 completed
2023-12-13 14:48:26,410 - INFO: Running Lab 4
2023-12-13 14:48:47,415 - INFO: Lab 4 completed
2023-12-13 14:48:49,939 - INFO: Running Lab 3
2023-12-13 14:49:11,187 - INFO: Lab 3 completed
2023-12-13 14:49:13,423 - INFO: Running Lab 2
2023-12-13 14:49:22,291 - INFO: Lab 2 completed
2023-12-13 14:49:23,104 - INFO: Running Lab 1
2023-12-13 14:50:42,961 - INFO: Running Lab 1
2023-12-13 14:53:01,425 - INFO: Running Lab 8
2023-12-13 15:04:01,235 - INFO: Running Lab 1
2023-12-13 15:07:37,153 - INFO: Running Lab 1
2023-12-13 15:09:39,620 - INFO: Running Lab 1
2023-12-13 15:09:45,393 - INFO: Lab 2 completed
2023-12-13 15:18:15,695 - INFO: Performing static code analysis with Pylint
2023-12-13 15:24:08,128 - INFO: Performing static code analysis with Pylint
2023-12-13 18:20:10,742 - INFO: Running Lab 7
2023-12-13 18:20:25,233 - INFO: Lab 7 completed
2023-12-13 18:20:29,007 - INFO: Running Lab 8
2023-12-13 18:22:36,656 - INFO: Running Lab 8
2023-12-13 18:29:56,161 - INFO: Running Lab 8
2023-12-13 18:33:34,989 - INFO: Running Lab 8
2023-12-13 18:36:17,160 - INFO: Running Lab 8
2023-12-13 18:36:23,661 - INFO: Running Lab 7
2023-12-13 18:36:52,415 - INFO: Lab 7 completed
2023-12-13 18:36:55,664 - INFO: Running Lab 8
2023-12-13 18:37:18,618 - INFO: Running Lab 8
2023-12-13 18:37:28,460 - INFO: Running Lab 7
2023-12-13 18:37:59,536 - INFO: Lab 7 completed
2023-12-13 18:38:01,600 - INFO: Running Lab 7
2023-12-13 18:38:10,522 - INFO: Lab 7 completed
2023-12-13 18:38:13,403 - INFO: Running Lab 2
2023-12-13 18:38:39,747 - INFO: Lab 2 completed
2023-12-13 18:38:43,955 - INFO: Running Lab 8
2023-12-14 11:19:06,612 - INFO: Running Lab 8
2023-12-14 11:19:15,264 - INFO: Running Lab 5
2023-12-14 11:20:05,466 - INFO: Lab 5 completed
2023-12-14 11:20:07,576 - INFO: Running Lab 7
2023-12-14 11:20:10,047 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E239420110>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:13,528 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E239421D10>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:27,327 - INFO: Running Lab 7
2023-12-14 11:20:29,039 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E58C8850>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:32,682 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E5921790>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:40,247 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E590FD90>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:46,242 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E5920F10>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:47,520 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E5928090>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:50,971 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E5929F10>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:52,077 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E592BD90>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:53,371 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E5935C90>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:20:59,109 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000222E592AD10>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:21:04,078 - INFO: Lab 7 completed
2023-12-14 11:21:06,403 - INFO: Running Lab 8
2023-12-14 11:23:11,069 - INFO: Running Lab 7
2023-12-14 11:23:12,675 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703E7F1B50>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:15,273 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED21CD0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:16,001 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703EC7D2D0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:16,584 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED20490>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:17,162 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED28450>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:17,856 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED2A310>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:18,403 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED34190>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:18,960 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED36050>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:19,501 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED2AFD0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:36,292 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED29ED0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:23:48,827 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED20510>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:24:05,758 - ERROR: Помилка обробки команди 2: If using all scalar values, you must pass an index
2023-12-14 11:24:06,685 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001703ED2BED0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:46:15,291 - INFO: Running Lab 7
2023-12-14 11:46:18,029 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000015E30113690>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:54:19,330 - INFO: Running Lab 7
2023-12-14 11:54:21,798 - ERROR: Помилка виклику API: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /todos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A047320790>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 11001] getaddrinfo failed)"))
2023-12-14 11:54:28,012 - INFO: Lab 7 completed
2023-12-14 11:54:29,721 - INFO: Running Lab 8
